#ifndef CONSTANTS_H
#define CONSTANTS_H

//#define END_ON_FIRST_SOLUTION

#ifdef _DEBUG
#define SET_SIZE 1
#else
//#define ORGINAL_SET 8
//#define SECONDARY_SET 16
#define THIRD_SET 8
#define SET_SIZE 8
#endif

#ifdef _DEBUG
	//#define OUTPUT_INTERMEDIATE_SOLUTION
	#define MAX_DEPTH_LIMIT 300
#else
	#define MAX_DEPTH_LIMIT 100000000
#endif

#define PARALLEL
//#define COMPLETE

enum VariableSoltuions { VARIABLE_NO_SOLUTION = 0x7FFFFFFF, MUST_NEGATIVE = -2, VARIABLE_NEGATIVE = -1, VARIABLE_UNKNOWN = 0, VARIABLE_POSITIVE = 1, MUST_POSITIVE = 2 };
enum SolvedStates { COMPLETED_UNKNOWN = 0x7FFFFFFF, COMPLETED_NO_SOLUTION = -2, NOT_COMPLETED_NO_SOLUTION = -1, NOT_COMPLETED = 0, NOT_COMPLETED_SOLUTION = 1, COMPLETED_SOLUTION = 2 };

#endif